version: "3.9"

services:
  influxdb_from:
    image: influxdb:1.7
    container_name: influxdb_from
    volumes:
      - influxdb_from:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUX_USERNAME: influxdb_from
      INFLUX_PASSWORD: password

  influxdb_to:
    image: influxdb:1.7
    container_name: influxdb_to
    volumes:
      - influxdb_to:/var/lib/influxdb
    ports:
      - "8087:8086"
    environment:
      INFLUX_USERNAME: influxdb_to
      INFLUX_PASSWORD: password

volumes:
  influxdb_from:
  influxdb_to: